// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'prod_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDSi2FojxaTP0X_UVuBU_1SRK5Whid3o',
    appId: '1:121704085836:web:fe34a2f849d131780e37e9',
    messagingSenderId: '121704085836',
    projectId: 'prod-counter',
    authDomain: 'prod-counter.firebaseapp.com',
    storageBucket: 'prod-counter.firebasestorage.app',
    measurementId: 'G-SDY81X6VM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvS2KIGPSQ4YAoxZg9dm4f8bSe19u3PxE',
    appId: '1:121704085836:android:0d703a14471b4b710e37e9',
    messagingSenderId: '121704085836',
    projectId: 'prod-counter',
    storageBucket: 'prod-counter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHClpow89KAqHXQCnWDPltWWIa5u19PE',
    appId: '1:121704085836:ios:096584652c31bd790e37e9',
    messagingSenderId: '121704085836',
    projectId: 'prod-counter',
    storageBucket: 'prod-counter.firebasestorage.app',
    iosBundleId: 'com.example.counterFlavor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaHClpow89KAqHXQCnWDPltWWIa5u19PE',
    appId: '1:121704085836:ios:096584652c31bd790e37e9',
    messagingSenderId: '121704085836',
    projectId: 'prod-counter',
    storageBucket: 'prod-counter.firebasestorage.app',
    iosBundleId: 'com.example.counterFlavor',
  );
}
