// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'dev_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWczc1pTJYmsRsGo1R4YOQO1xOmsZstq8',
    appId: '1:1011853729847:web:65cac7182ea3349ed61fb2',
    messagingSenderId: '1011853729847',
    projectId: 'dev-counter',
    authDomain: 'dev-counter.firebaseapp.com',
    storageBucket: 'dev-counter.firebasestorage.app',
    measurementId: 'G-J3M5FLFCPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA60KMFjJMRqwQ8LbAZfKuPGT7VrZ9V_8I',
    appId: '1:1011853729847:android:71f4b4dacf6cf4eed61fb2',
    messagingSenderId: '1011853729847',
    projectId: 'dev-counter',
    storageBucket: 'dev-counter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsmcJ1BxYij7uRvE7Ag3axmNqFKBN6yk8',
    appId: '1:1011853729847:ios:af87912e24c90df1d61fb2',
    messagingSenderId: '1011853729847',
    projectId: 'dev-counter',
    storageBucket: 'dev-counter.firebasestorage.app',
    iosBundleId: 'com.example.counterFlavor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsmcJ1BxYij7uRvE7Ag3axmNqFKBN6yk8',
    appId: '1:1011853729847:ios:af87912e24c90df1d61fb2',
    messagingSenderId: '1011853729847',
    projectId: 'dev-counter',
    storageBucket: 'dev-counter.firebasestorage.app',
    iosBundleId: 'com.example.counterFlavor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWczc1pTJYmsRsGo1R4YOQO1xOmsZstq8',
    appId: '1:1011853729847:web:af1dd69d09dc5236d61fb2',
    messagingSenderId: '1011853729847',
    projectId: 'dev-counter',
    authDomain: 'dev-counter.firebaseapp.com',
    storageBucket: 'dev-counter.firebasestorage.app',
    measurementId: 'G-8E75NHY312',
  );
}
